//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Гостиница
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int ИДКлиента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Комментарий { get; set; }
        public int ИДНомера { get; set; }
    
        public virtual Номера Номера { get; set; }

        public Клиенты()
        {

        }

        public Клиенты(string ф, string и, string о, string к, int ид)
        {
            Фамилия = ф;
            Имя = и;
            Отчество = о;
            Комментарий = к;
            ИДНомера = ид;
        }
    }
}
