//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Гостиница
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номера
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Номера()
        {
            this.Клиенты = new HashSet<Клиенты>();
        }
    
        public int ИДНомера { get; set; }
        public string НазваниеНомера { get; set; }
        public int Вместимость { get; set; }
        public string Комфортность { get; set; }
        public decimal Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиенты> Клиенты { get; set; }

        public Номера(string н, int в, string к, decimal ц)
        {
            НазваниеНомера = н;
            Вместимость = в;
            Комфортность = к;
            Цена = ц;
        }
    }
}
